// Standard chart documents, workflows and documentation views every practice starts with.
// Practices customise them in Settings → Documentation settings (the designer), or add their own.
import { slugId, type DocumentSection, type FieldDef, type FieldType } from "./chart-forms";

type Spec = Omit<FieldDef, "id">;
type Opt = Partial<Pick<FieldDef, "required" | "help" | "unit" | "width">>;

const mk = (type: FieldType) => (label: string, o: Opt = {}): Spec => ({ label, type, ...o });
const t = mk("text");
const ta = mk("textarea");
const d = mk("date");
const yn = mk("yesno");
const cb1 = mk("checkbox");
const h = mk("heading");
const note = mk("note");
const n = (label: string, unit?: string, o: Opt = {}): Spec => ({ label, type: "number", unit, ...o });
const sel = (label: string, options: string[], o: Opt = {}): Spec => ({ label, type: "select", options, ...o });
const rad = (label: string, options: string[], o: Opt = {}): Spec => ({ label, type: "radio", options, ...o });
const cbs = (label: string, options: string[], o: Opt = {}): Spec => ({ label, type: "checkboxes", options, ...o });
// Plan-of-care statements: each ticked one takes a comment, a status and a status date.
const care = (label: string, options: string[], o: Opt = {}): Spec => ({ label, type: "careitems", options, ...o });
// The patient's open wounds as tick boxes.
const wnd = mk("wounds");
const score = (label: string, bands: string[]): Spec => ({ label, type: "score", options: bands });
const req: Opt = { required: true };
const half: Opt = { width: "half" };

function withIds(specs: Spec[]): FieldDef[] {
  const taken = new Set<string>();
  return specs.map((s) => ({ ...s, id: slugId(s.label, taken) }));
}

export type CatalogTemplate = {
  key: string;
  name: string;
  section: DocumentSection;
  kind: "BUILTIN" | "FORM";
  audience?: "STAFF" | "PATIENT";
  description?: string;
  perWound?: boolean;
  signatureRequired?: boolean;
  critical?: boolean;
  inProgressNote?: boolean;
  fields?: FieldDef[];
};

const builtin = (key: string, name: string, section: DocumentSection, description?: string): CatalogTemplate => ({
  key,
  name,
  section,
  kind: "BUILTIN",
  description,
});
const form = (key: string, name: string, section: DocumentSection, specs: Spec[], extra: Partial<CatalogTemplate> = {}): CatalogTemplate => ({
  key,
  name,
  section,
  kind: "FORM",
  fields: withIds(specs),
  ...extra,
});

const WOUND_PRODUCTS = [
  "Alginate",
  "Collagen",
  "Foam",
  "Hydrocolloid",
  "Hydrogel",
  "Silver antimicrobial",
  "Honey",
  "Cadexomer iodine",
  "Enzymatic debrider (collagenase)",
  "Gauze / ABD",
  "Transparent film",
  "Compression wrap",
  "Skin substitute / CTP",
  "NPWT",
];

const HBO_INDICATIONS = [
  "Diabetic foot ulcer, Wagner grade 3+ (failed 30 days of standard care)",
  "Chronic refractory osteomyelitis",
  "Delayed radiation injury (soft tissue / bone)",
  "Compromised skin graft or flap",
  "Necrotising soft tissue infection",
  "Crush injury / acute traumatic ischaemia",
  "Gas gangrene",
  "Carbon monoxide poisoning",
  "Decompression sickness / air embolism",
  "Acute peripheral arterial insufficiency",
  "Other (document)",
];
const YES_NO_NA = ["Yes", "No", "N/A"];
const PULSE = ["Palpable", "Diminished", "Doppler only", "Absent", "Not assessed"];
const PAIN_0_10 = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"];
const TREATMENT_RESPONSE = ["Procedure was tolerated well", "Procedure was tolerated with difficulty", "Procedure was stopped — patient unable to tolerate"];
const COMPRESSION_DEVICES = ["Unna's or Duke Boot", "Multi-layer compression wrap", "Compression stockings", "Tubular bandage (Tubigrip)", "Short-stretch bandage", "Pneumatic compression pump", "Other"];
const OFFLOADING_DEVICES = ["Felt and Foam", "Static Overlay", "Multipodus / heel protector boots", "Total contact cast", "CAM / walking boot", "Post-op / healing shoe", "Wheelchair cushion", "Pillows", "Other"];
// One Review of Systems block: what the patient complains of (+) and what they deny (-).
const rosSystem = (system: string, symptoms: string[]): Spec[] => [h(system), cbs(`${system} — patient complains of (+)`, symptoms, half), cbs(`${system} — patient denies (-)`, symptoms, half)];
// Left / right pair of the same finding.
const leftRight = (label: string, options: string[]): Spec[] => [sel(`Left — ${label}`, options, half), sel(`Right — ${label}`, options, half)];

// Primary-care screening questionnaires.
const FREQ_0_3 = ["Not at all|0", "Several days|1", "More than half the days|2", "Nearly every day|3"];
const PHQ9_ITEMS = [
  "Little interest or pleasure in doing things",
  "Feeling down, depressed, or hopeless",
  "Trouble falling or staying asleep, or sleeping too much",
  "Feeling tired or having little energy",
  "Poor appetite or overeating",
  "Feeling bad about yourself — or that you are a failure or have let yourself or your family down",
  "Trouble concentrating on things, such as reading the newspaper or watching television",
  "Moving or speaking so slowly that other people could have noticed; or the opposite — being so fidgety or restless that you have been moving around a lot more than usual",
  "Thoughts that you would be better off dead or of hurting yourself in some way",
];
const GAD7_ITEMS = [
  "Feeling nervous, anxious, or on edge",
  "Not being able to stop or control worrying",
  "Worrying too much about different things",
  "Trouble relaxing",
  "Being so restless that it is hard to sit still",
  "Becoming easily annoyed or irritable",
  "Feeling afraid, as if something awful might happen",
];
// One preventive-care line: status today plus the date of the last one.
const screening = (label: string): Spec[] => [sel(label, ["Up to date", "Due — ordered today", "Due — declined", "Not applicable", "Not discussed"], half), d(`${label} — last done`, half)];

// Templates whose standard layout changed to follow the practice's visit report (Review of Systems, Physician Orders...).
// A practice that never edited or used the old layout gets the new one in place; otherwise it is added beside the old.
export const REVISED_TEMPLATES = ["physician_orders", "allergy_list", "ctp", "lower_extremity", "physical_exam_systems", "plan_of_care", "ros", "telemedicine_consent"];

export const STANDARD_TEMPLATES: CatalogTemplate[] = [
  // ---- Documentation ----
  builtin("cc", "Chief Complaint / HPI", "DOCUMENTATION"),
  builtin("vitals", "Vital Signs", "DOCUMENTATION"),
  builtin("wounds", "Active Wounds", "DOCUMENTATION"),
  builtin("problems", "Problem List", "DOCUMENTATION"),
  form(
    "physician_orders",
    "Physician Orders",
    "DOCUMENTATION",
    [
      cb1("Verbal / phone orders"),
      wnd("Select wound(s) for these orders", { help: "Tick every wound the orders below apply to. Leave all unticked for an order that is not wound specific." }),

      h("Wound care cleansing"),
      cbs("Wound care cleansing", [
        "Cleanse wound with Normal Saline",
        "Cleanse wound with wound cleanser of choice",
        "Cleanse wound with Dakin's solution",
        "Cleanse wound with Dakin's solution half strength",
        "Cleanse wound daily",
        "Cleanse wound 2x per day",
        "Cleanse wound every other day",
        "May cleanse wound in shower",
        "Do not shower or bath",
      ]),
      t("Cleanse wound with / other cleansing instructions"),

      h("Topical"),
      ta("Topical", { help: "e.g. Apply Gentamicin ointment to wound bed — which days" }),

      h("Wound packing"),
      cbs("Wound packing", ["Loosely pack with 1/2\" iodoform packing or comparable", "Pack wound daily", "Pack wound 2x per week", "Pack wound every other day"]),
      t("Pack wound / tunneling with", half),

      h("Wound dressing choice"),
      cbs("Wound dressing choice", [
        "Cellular Tissue applied to wound site today, LEAVE IN PLACE. Change outer dressing as ordered.",
        "Cellular Tissue applied today. Dressing to remain dry and intact. Hold Home Health Wound Care Visit for one week. DO NOT REMOVE DRESSING",
        "Actigraft applied to wound site today, LEAVE IN PLACE. Change outer dressing as ordered.",
        "Actigraft applied today. Dressing to remain dry and intact. Hold Home Health Wound Care Visit for one week. DO NOT REMOVE DRESSING",
        "Apply Skin Prep or similar skin protectant at periwound area",
        "Apply Calcium Alginate",
        "Apply Calcium Alginate with Silver dressing",
        "Apply Collagen",
        "Apply Collagen with Silver dressing",
        "Apply Bordered Gauze",
        "Apply Hydrocolloid",
        "Apply Foam dressing",
        "Apply Foam with Silver dressing",
        "Apply Bordered Foam with Silver dressing",
        "Apply Bordered Foam dressing",
        "Apply Non Adhesive Wound Veil (contact layer) directly to wound",
        "Apply Hydrofiber dressing",
        "Apply Hydrofiber with silver dressing",
        "Apply 4x4 Gauze",
        "Apply ABD pad.",
        "Apply steri-strips",
        "Apply Iodoflex or comparable.",
        "Apply Hydrofera Blue or comparable.",
        "Apply Aquacel Ag or comparable Hydrofiber with silver dressing",
        "Apply Aquacel or comparable Hydrofiber dressing",
        "Apply Optifoam AG dressing or comparable foam dressing with silver.",
        "Apply Xeroform or comparable petroleum wound veil",
        "Cover with moist to dry dressing.",
        "Cover with bordered dressing",
        "Cover with bordered foam dressing",
        "Secure dressing with rolled gauze and tape.",
        "Secure dressing with Coban or comparable",
        "Reinforce dressing with Ace Wrap or comparable",
        "Reinforce dressing with Netting",
        "Wound dressing to be changed daily",
        "Wound dressing to be changed every other day.",
        "Wound dressing to be changed twice weekly.",
        "Wound dressing to be changed three times weekly.",
        "Change dressing as needed for soiling, saturation, or accidental removal.",
      ]),
      t("Cover / secure wound with", half),
      t("Wound dressing frequency change as follows", half),

      h("Compression therapy"),
      cbs("Compression", ["Left Leg", "Right Leg", "Apply Unna Boot and cover with rolled gauze and coban or comparable", "Multi-layer compression wrap", "Compression stockings", "Elevate legs whenever possible"]),
      t("Compression instructions"),

      h("Negative pressure wound therapy (NPWT)"),
      ta("NPWT order", { help: "Pressure setting, mode, canister and dressing change frequency" }),

      h("DME equipment"),
      cbs("DME equipment", ["Group 1 offloading device", "Group 2 offloading device", "Group 3 offloading device"]),
      t("Other DME"),

      h("Pressure relief / offloading"),
      cbs("Pressure relief / offloading", ["Offloading Foam Heel Boots", "Facility Pressure Injury Prevention Protocol", "Wheelchair Pressure Redistribution Cushion", "Multipodus Boot", "Camwalker", "Roho Cushion", "OrthoWedge Shoe"]),
      t("Other offloading"),

      h("Pressure redistribution mattress"),
      cbs("Pressure redistribution mattress", [
        "Continue Group 1 pressure reducing support surface; nutrition optimized and regular repositioning schedule followed",
        "Group 2 pressure relieving support surface — wounds have not improved on a Group 1 surface for over 30 days",
        "Group 3 Air Immersion Mattress — wounds continue to deteriorate on a Group 2 surface; patient is bed-bound",
        "Continue Group 3 Air Immersion Mattress",
        "Continue Group 3 Air Fluidized Bed",
      ]),
      ta("Mattress justification", { help: "Time on the current surface, nutrition, repositioning schedule, and what was discussed with patient, family and caregiver" }),

      h("Diabetic shoes and fillers"),
      ta("Diabetic shoes and fillers"),

      h("Ultrasound Mist treatment order"),
      cbs("Ultrasound Mist treatment order", [
        "Ultrasound Mist Therapy to be performed 2X/week X 3 weeks OR 2x/week for a total of 6 treatments (whichever comes first)",
        "Ultrasound Mist Therapy to be performed 3x/week X 2 weeks OR 3x/week for a total of 6 treatments (whichever comes first)",
        "Ulcers/Wounds/Burns which have failed conventional debridement and are too painful for sharp/excisional debridement.",
        "Ulcers/Wounds/Burns with any documented contraindications to sharp/excisional debridement.",
        "Ulcers/Wounds/Burns with documented evidence of no signs of improvement after 30 days of standard wound care.",
        "Discontinue Ultrasound Mist Therapy",
      ]),

      h("Ankle Brachial Index"),
      ta("Ankle Brachial Index order"),

      h("Home health"),
      cbs("Home health", [
        "Patient is eligible for home health and meets the criteria for home health services based on patient's homebound status.",
        "Skilled Nursing is required for wound care",
        "Home Health: Patient to be seen by home health daily",
        "Home Health: Patient to be seen by home health 1x per week prior to next wound care visit",
        "Home Health: Patient to be seen by home health 2x per week prior to next wound care visit",
        "Home Health: Patient to be seen by home health 3x per week prior to next wound care visit",
        "Continue current wound dressing regimen until follow-up evaluation with the wound care provider",
      ]),
      t("Home health agency / facility", half),
      ta("Home health instructions", { help: "Include the number to call if unsure" }),

      h("Telehealth and treatment plan orders"),
      cbs("Telehealth and treatment plan orders", [
        "1A: Patient does not have a wound and/or does not require advanced wound care treatment. OK to discharge.",
        "1B: Conservative wound care needed. Follow-up as needed for 4-6 weeks; between wound care visits, cleanse wound(s) daily, apply the ordered dressing and offload the affected area.",
        "2A: Moderate wound care needed, partial thickness wound(s). Provider to follow up and provide wound care as needed for about 10 weeks.",
        "2B: Moderate wound care needed, full thickness wound(s). Provider to follow up and perform surgical debridement as needed, wound care weekly for approximately 12-14 weeks.",
        "3A: Advanced wound care needed, full thickness wound(s). Provider to follow up and perform Ultrasound Mist Therapy 2-3x per week for 6 weeks.",
        "3B: Advanced wound care needed, full thickness wound(s). Provider to perform surgical debridement/wound care weekly for 12 weeks with possible skin substitute if indicated.",
        "WET wound protocol: cleanse with wound cleanser 3x/weekly, cover with calcium alginate of choice, cover with bordered foam dressing; secure with rolled gauze and tape if necessary.",
        "DRY wound protocol: cleanse with wound cleanser 3x/weekly, cover with non-adherent petrolatum-based gauze dressing or wound veil, cover with bordered gauze dressing; secure with rolled gauze and tape if necessary.",
      ]),

      h("Products"),
      cbs("Commonly used products", ["Normal Saline", "Drawtex"]),
      ta("Products ordered", { help: "Product name, brand or category, size and quantity" }),

      h("Ancillary services"),
      cbs("Ancillary services", ["Laboratory", "Radiology", "Vascular studies (ABI / TBI)", "Wound biopsy / culture", "Nutrition consult", "Physical therapy", "Referral"]),
      ta("Tests / studies ordered", { help: "e.g. Bacteria identified in Tissue by Biopsy culture; XR foot 3 views, left" }),
      cbs("Goes with the order", ["Prescription", "Discharge instructions", "Referred away"]),
      t("ICD-10 for the order", half),

      h("Advanced treatments"),
      t("Cell and tissue based product", half),
      ta("Cell and tissue based product order"),
      ta("HBO order"),
      ta("Pneumatic compression order"),

      h("Other orders"),
      ta("Other provider orders"),

      h("Follow up"),
      sel("Patient follow up visit in", ["One week", "Two weeks", "Three weeks", "One month", "PRN"], half),
      d("Provider is scheduled to see patient on", half),
      ta("Notes"),
    ],
    { signatureRequired: true }
  ),
  builtin("exam", "Physical Exam", "DOCUMENTATION"),
  builtin("assessment", "Assessment & Plan of Care", "DOCUMENTATION"),
  builtin("meds", "Medications, Orders & Labs", "DOCUMENTATION"),

  // ---- Procedure & treatment ----
  form("procedures", "Procedures", "PROCEDURE", [
    sel("Procedure", [
      "Selective debridement",
      "Excisional debridement (subcutaneous)",
      "Excisional debridement (muscle / fascia)",
      "Excisional debridement (bone)",
      "Skin substitute application",
      "Negative pressure wound therapy",
      "Multi-layer compression",
      "Total contact cast",
      "Unna boot",
      "Low-frequency ultrasound (MIST)",
      "Biopsy",
      "Other",
    ], req),
    t("Wound / site", half),
    t("Performed by", half),
    cbs("Consent & time-out", ["Consent obtained", "Time-out performed", "Patient identified x2", "Site marked"]),
    sel("Anesthesia", ["None", "Topical lidocaine", "Local injection", "Other"], half),
    sel("Instrument", ["Curette", "Scalpel", "Forceps & scissors", "Other"], half),
    sel("Tissue removed", ["Slough", "Eschar", "Biofilm", "Fibrin", "Subcutaneous tissue", "Muscle / fascia", "Bone"], half),
    sel("Depth of debridement", ["Epidermis / dermis", "Subcutaneous", "Muscle / fascia", "Bone"], half),
    n("Area debrided", "cm²", half),
    sel("Bleeding", ["None", "Minimal", "Moderate", "Heavy"], half),
    sel("Hemostasis", ["Pressure", "Silver nitrate", "Electrocautery", "Not required"], half),
    rad("Patient tolerance", ["Well", "Fair", "Poor"], half),
    ta("Procedure note", req),
  ]),
  form(
    "treatment_notes",
    "Treatment Notes",
    "PROCEDURE",
    [
      sel("Treatment", ["Dressing change", "Low-frequency ultrasound (MIST)", "Compression", "NPWT change", "Skin substitute", "Offloading", "Other"], req),
      cbs("Cleansed with", ["Normal saline", "Wound cleanser", "Hypochlorous acid", "Dakin's", "Povidone iodine"]),
      cbs("Primary dressing", WOUND_PRODUCTS),
      cbs("Secondary dressing", ["Bordered foam", "ABD pad", "Gauze", "Kerlix / roll gauze", "Tape", "Compression"]),
      n("Treatment time", "minutes", half),
      rad("Patient tolerance", ["Well", "Fair", "Poor"], half),
      ta("Treatment note", req),
    ],
    { perWound: true }
  ),
  builtin("multiwound", "Multi Wound Chart", "PROCEDURE"),

  // ---- Progress note / billing ----
  builtin("progress", "Progress Note", "PROGRESS"),
  builtin("superbill", "SuperBill", "BILLING"),
  builtin("signatures", "Attestation & Signatures", "BILLING"),

  // ---- Additional documents ----
  form("prescriptions", "Prescriptions", "ADDITIONAL", [
    t("Medication", req),
    t("Strength / form", half),
    t("Quantity", half),
    t("Sig (directions)", req),
    n("Refills", undefined, half),
    cb1("Dispense as written", half),
    t("Pharmacy"),
    ta("Notes"),
  ]),
  form("abuse_screening", "Abuse Screening Assessment", "ADDITIONAL", [
    yn("Does anyone at home hurt, hit or threaten you?", req),
    yn("Are you afraid of anyone close to you?", req),
    yn("Has anyone taken your money or belongings without permission?"),
    yn("Has anyone failed to help you with care you need?"),
    yn("Signs of neglect or unexplained injuries observed?"),
    sel("Outcome", ["Negative screen", "Positive screen — referred", "Patient declined"], req),
    ta("Referral / action taken"),
  ]),
  form("advance_directives", "Advanced Directives", "ADDITIONAL", [
    yn("Does the patient have an advance directive?", req),
    cbs("Documents on file", ["Living will", "Healthcare power of attorney", "POLST / MOLST", "DNR order"]),
    sel("Code status", ["Full code", "DNR", "DNR / DNI", "Comfort care only"], req),
    t("Healthcare agent", half),
    t("Agent phone", half),
    yn("Information provided on advance directives?"),
    ta("Notes"),
  ]),
  form("code_status", "Code Status / DNR", "ADDITIONAL", [
    rad("Code status", ["Full code", "DNR", "DNR / DNI", "Comfort measures only", "Unknown"], req),
    yn("DNR on file", half),
    ta("Notes"),
  ]),
  form("allergy_list", "Allergy List", "ADDITIONAL", [
    yn("No known drug allergies (NKDA)", half),
    yn("Latex allergy", half),
    ta("Active allergies", { help: "One per line: allergen — reaction — severity" }),
    ta("Allergy notes"),
    yn("Allergies reviewed with patient", req),
  ]),
  form(
    "attestation_statements",
    "Attestation Statements",
    "ADDITIONAL",
    [
      cbs("Attestations", [
        "I personally performed the services documented",
        "Services were medically necessary",
        "Scribe documented in my presence; I reviewed and agree",
        "Incident-to requirements met (direct supervision)",
        "Teaching physician present for key portions",
      ], req),
      ta("Additional statement"),
    ],
    { signatureRequired: true }
  ),
  form(
    "ctp",
    "Cell and Tissue Based Product Application",
    "ADDITIONAL",
    [
      t("Cell and/or tissue-based product", { ...req, help: "e.g. Membrane wrap" }),
      t("Performed by", half),
      n("Application number", undefined, half),
      yn("Time-out taken", half),
      sel("Location", ["trunk / arms / legs", "face / scalp / eyelids / mouth / neck / ears / orbits / genitalia / hands / feet / multiple digits"], half),
      n("Application area", "sq cm", half),
      n("Product applied", "sq cm", half),
      n("Product waste", "sq cm", half),
      sel("Waste reason", ["Excess", "Product size larger than wound", "Contaminated", "Other"], half),
      h("Lot / order numbers"),
      t("Lot #", half),
      t("Order #", half),
      d("Expiration date", half),
      t("Lot 2 #", half),
      t("Order 2 #", half),
      d("Expiration date 2", half),
      t("Lot 3 #", half),
      t("Order 3 #", half),
      d("Expiration date 3", half),
      t("Lot 4 #", half),
      t("Order 4 #", half),
      d("Expiration date 4", half),
      h("Application"),
      t("Time of application", { ...half, help: "e.g. 1:30 PM" }),
      yn("Fenestrated", half),
      yn("Secured", half),
      t("Secured with", half),
      yn("Dressing applied", half),
      t("Dressing applied — which", { ...half, help: "e.g. Collagen / Vaseline gauze / Unna boot" }),
      sel("Procedural pain", PAIN_0_10, half),
      sel("Post procedural pain", PAIN_0_10, half),
      sel("Response to treatment", TREATMENT_RESPONSE),
      h("Medical necessity statements"),
      cbs("Statements that apply", [
        "Subsequent application: The ulcer has been responding to the treatment with improvement to both tissue and measurements. Treatment will continue with standard wound care in conjunction with continued assessment, treatment and reapplication of the cellular tissue product if appropriate in accordance to the FDA approved product indication for use, as it is medically necessity as a wound covering and barrier.",
        "Vascular assessment: Based on vascular assessment and testing, patient's vascular status falls within the standard requirement for healing.",
        "Debridement & infection: Patient has been undergoing serial debridement. Ulcer remains clean and moist with appropriate dressings. Ulcer is free of infection.",
        "Nutrition: Patient's nutrition, which is being optimized, has been discussed and education provided. Patient's blood glucose is well controlled as evidence by an optimal A1C. Patient encouraged to continue to be compliant with diet recommendations and proper monitoring.",
        "Non-smoker: Patient is a non-smoker.",
        "Smoking cessation: Patient has been counselled on smoking cessation and its effect on wound healing.",
        "Offloading: Patient continues to be compliant with wound offloading. Patient educated on importance of continued compliance of offloading to promoting wound healing.",
        "Compression: Edema is being controlled with >20mmHg. Patient educated on importance of continued compliance of limb elevation and compression to promote edema control and wound healing.",
        "Plan and medical necessity: Product was applied strictly following the FDA approved instructions found on the product insert. The plan going forward is to use the above cellular tissue product in accordance to the FDA approved product indication for use, as it is medically necessity as a wound covering and barrier. Ulcer will continue to receive standard wound care in conjunction with continued assessment, treatment and reapplication of the CTP if appropriate.",
      ]),
      cbs("Conservative care failed (≥4 weeks) — first application", ["Offloading", "Compression", "Moist wound care", "Debridement", "Infection control", "Glycemic control"]),
      ta("Additional notes"),
    ],
    { perWound: true, signatureRequired: true }
  ),
  form("diabetic_foot_exam", "Diabetic Foot Exam", "ADDITIONAL", [
    h("Monofilament (10 g)"),
    rad("Right foot sensation", ["Intact", "Diminished", "Absent"], half),
    rad("Left foot sensation", ["Intact", "Diminished", "Absent"], half),
    h("Pulses"),
    sel("Right dorsalis pedis", ["2+ normal", "1+ diminished", "Absent", "Doppler only"], half),
    sel("Left dorsalis pedis", ["2+ normal", "1+ diminished", "Absent", "Doppler only"], half),
    sel("Right posterior tibial", ["2+ normal", "1+ diminished", "Absent", "Doppler only"], half),
    sel("Left posterior tibial", ["2+ normal", "1+ diminished", "Absent", "Doppler only"], half),
    cbs("Findings", ["Callus", "Deformity", "Charcot foot", "Nail dystrophy", "Fissures", "Dry skin", "Tinea", "Amputation"]),
    sel("Risk category (IWGDF)", ["0 — very low", "1 — low", "2 — moderate", "3 — high"], req),
    ta("Footwear / education"),
  ]),
  form("discharge_instructions", "Discharge Instructions", "ADDITIONAL", [
    ta("Wound care at home", req),
    cbs("Call us if", ["Fever over 100.4°F", "Increased redness or swelling", "Foul odor", "Increased drainage", "Increased pain", "Bleeding that won't stop"]),
    ta("Activity / diet"),
    d("Follow-up date", half),
    yn("Patient / caregiver verbalized understanding", { ...req, width: "half" }),
  ]),
  form("em_time", "E&M Time Statements", "ADDITIONAL", [
    n("Total time on date of service", "minutes", req),
    cbs("Activities included", [
      "Reviewing records / tests",
      "History & exam",
      "Counseling patient / family",
      "Ordering tests / procedures",
      "Care coordination",
      "Documenting in the record",
    ]),
    ta("Time statement", { help: "e.g. I spent 35 minutes on the date of service, excluding separately billed procedures." }),
  ]),
  form("education_goals", "Education Goals", "ADDITIONAL", [
    cbs("Topics", ["Wound care", "Nutrition", "Offloading", "Compression", "Glycemic control", "Smoking cessation", "Infection signs", "Medication"]),
    ta("Goals", req),
    rad("Goal status", ["Met", "Progressing", "Not met"]),
  ]),
  form("educational_needs", "Educational Needs Assessment / Barriers to Learning", "ADDITIONAL", [
    cbs("Barriers to learning", ["None", "Language", "Hearing", "Vision", "Cognitive", "Literacy", "Emotional", "Cultural / religious", "Physical"]),
    sel("Preferred learning method", ["Verbal", "Written", "Demonstration", "Video"], half),
    yn("Interpreter needed", half),
    t("Primary learner (patient / caregiver)"),
    ta("Notes"),
  ]),
  form("fall_risk", "Fall Risk Assessment (Morse)", "ADDITIONAL", [
    rad("History of falling (3 months)", ["No|0", "Yes|25"], req),
    rad("Secondary diagnosis", ["No|0", "Yes|15"], req),
    rad("Ambulatory aid", ["None / bed rest / nurse assist|0", "Crutches / cane / walker|15", "Furniture|30"], req),
    rad("IV / heparin lock", ["No|0", "Yes|20"], req),
    rad("Gait", ["Normal / bed rest / wheelchair|0", "Weak|10", "Impaired|20"], req),
    rad("Mental status", ["Oriented to own ability|0", "Forgets limitations|15"], req),
    score("Morse fall score", ["24|No risk", "44|Low risk", "125|High risk"]),
    ta("Fall precautions"),
  ]),
  form("family_history", "Family History", "ADDITIONAL", [
    cbs("Conditions in family", ["Diabetes", "Heart disease", "Hypertension", "Stroke", "Cancer", "Peripheral vascular disease", "Kidney disease", "Clotting disorder"]),
    ta("Details (relative — condition)"),
  ]),
  form("immunizations", "Immunizations", "ADDITIONAL", [
    d("Tetanus (Td / Tdap)", half),
    d("Influenza", half),
    d("Pneumococcal", half),
    d("COVID-19", half),
    d("Hepatitis B", half),
    yn("Immunizations reviewed", half),
    ta("Notes"),
  ]),
  builtin("inactivewounds", "Inactive Wounds", "ADDITIONAL"),
  form("lower_extremity", "Lower Extremity Assessment", "ADDITIONAL", [
    h("Edema assessment"),
    ...leftRight("Edema", ["No", "Yes — 1+", "Yes — 2+", "Yes — 3+", "Yes — 4+"]),
    ...leftRight("Compression device in use", ["Yes", "No"]),
    ...leftRight("Compression device used correctly", YES_NO_NA),
    ...leftRight("Compression device used", COMPRESSION_DEVICES),
    h("Vascular assessment — pulses"),
    ...leftRight("Popliteal", PULSE),
    ...leftRight("Posterior tibial", PULSE),
    ...leftRight("Dorsalis pedis", PULSE),
    h("Extremity colors, hair growth, and conditions"),
    ...leftRight("Extremity color", ["Normal", "Pigmented", "Pale", "Red", "Cyanotic", "Mottled"]),
    ...leftRight("Hair growth on extremity", ["Yes", "No"]),
    ...leftRight("Temperature of extremity", ["Warm", "Cool", "Cold", "Hot"]),
    ...leftRight("Capillary refill", ["< 3 seconds", "> 3 seconds"]),
    ...leftRight("Erythema", ["Yes", "No"]),
    ...leftRight("Dependent rubor", ["Yes", "No"]),
    ...leftRight("Hyperpigmentation", ["Yes", "No"]),
    ...leftRight("Lipodermatosclerosis", ["Yes", "No"]),
    h("Off-loading"),
    ...leftRight("Off-loading device in use", ["Yes", "No"]),
    ...leftRight("Off-loading device used correctly", YES_NO_NA),
    ...leftRight("Off-loading device used", OFFLOADING_DEVICES),
    h("Measurements"),
    n("Left ABI", undefined, half),
    n("Right ABI", undefined, half),
    n("Left calf circumference", "cm", half),
    n("Right calf circumference", "cm", half),
    ta("Notes"),
  ]),
  form("lymphedema", "Lymphedema", "ADDITIONAL", [
    sel("Affected limb", ["Right leg", "Left leg", "Both legs", "Right arm", "Left arm"], req),
    sel("Stage", ["0 — latent", "I — reversible", "II — spontaneously irreversible", "III — elephantiasis"], half),
    yn("Stemmer sign positive", half),
    n("Circumference — ankle", "cm", half),
    n("Circumference — calf", "cm", half),
    cbs("Treatment", ["Compression garment", "Multi-layer wrapping", "Manual lymph drainage", "Pneumatic compression", "Elevation", "Exercise"]),
    ta("Notes"),
  ]),
  form("medical_history", "Medical History", "ADDITIONAL", [
    cbs("Conditions", [
      "Diabetes type 1",
      "Diabetes type 2",
      "Hypertension",
      "CAD",
      "CHF",
      "PVD / PAD",
      "Venous insufficiency",
      "COPD",
      "CKD",
      "Dialysis",
      "Stroke",
      "Paralysis / SCI",
      "Obesity",
      "Malnutrition",
      "Dementia",
      "Immunosuppression",
      "Cancer",
    ]),
    n("Last HbA1c", "%", half),
    t("Smoking status", half),
    ta("Other history"),
  ]),
  form("narrative_notes", "Narrative Notes", "ADDITIONAL", [ta("Narrative note", req)]),
  form(
    "npwt",
    "Negative Pressure Wound Therapy",
    "ADDITIONAL",
    [
      t("Device", half),
      sel("Mode", ["Continuous", "Intermittent", "Variable"], half),
      n("Pressure", "mmHg", half),
      sel("Foam / filler", ["Black (GranuFoam)", "White (VersaFoam)", "Silver", "Gauze"], half),
      n("Pieces of foam removed", undefined, half),
      n("Pieces of foam placed", undefined, half),
      n("Canister output", "mL", half),
      sel("Seal", ["Intact", "Leak repaired", "Leak — changed"], half),
      ta("Notes"),
    ],
    { perWound: true }
  ),
  form("nutrition_risk", "Nutrition Risk Assessment (MNA-SF)", "ADDITIONAL", [
    rad("Food intake declined over past 3 months", ["Severe decrease|0", "Moderate decrease|1", "No decrease|2"], req),
    rad("Weight loss in past 3 months", ["More than 3 kg|0", "Does not know|1", "1–3 kg|2", "No weight loss|3"], req),
    rad("Mobility", ["Bed or chair bound|0", "Gets out of bed / chair but does not go out|1", "Goes out|2"], req),
    rad("Psychological stress or acute disease (3 months)", ["Yes|0", "No|2"], req),
    rad("Neuropsychological problems", ["Severe dementia or depression|0", "Mild dementia|1", "None|2"], req),
    rad("BMI", ["Less than 19|0", "19 to less than 21|1", "21 to less than 23|2", "23 or more|3"], req),
    score("Screening score", ["7|Malnourished", "11|At risk of malnutrition", "14|Normal nutritional status"]),
    cbs("Interventions", ["Dietitian referral", "Protein supplement", "Multivitamin", "Weekly weights"]),
  ]),
  form("offloading", "Offloading and Support Surface Surveillance", "ADDITIONAL", [
    cbs("Offloading devices", ["Heel boots", "Wedges / pillows", "Total contact cast", "Walking boot", "Post-op shoe", "Felt padding", "Wheelchair cushion"]),
    sel("Support surface", ["Standard mattress", "Pressure-redistribution foam", "Alternating pressure", "Low air loss", "Air-fluidized"], half),
    sel("Turning schedule", ["Every 2 hours", "Every 3 hours", "Every 4 hours", "Independent"], half),
    yn("Device in use and appropriate", req),
    ta("Notes"),
  ]),
  form("pain_assessment", "Pain Assessment", "ADDITIONAL", [
    sel("Pain scale", ["0 — no pain", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10 — worst pain"], req),
    t("Location", half),
    cbs("Quality", ["Aching", "Burning", "Sharp", "Stabbing", "Throbbing", "Shooting"]),
    sel("Frequency", ["Constant", "Intermittent", "With dressing changes only"], half),
    t("Relieved by", half),
    ta("Pain management plan"),
  ]),
  form("caregiver_education", "Patient Care Giver Education", "ADDITIONAL", [
    cbs("Education provided", ["Dressing change technique", "Signs of infection", "Offloading", "Nutrition", "Hand hygiene", "Medication", "When to call"]),
    t("Taught to", half),
    sel("Method", ["Verbal", "Demonstration", "Written", "Teach-back"], half),
    rad("Understanding", ["Verbalized", "Demonstrated", "Needs reinforcement"], req),
  ]),
  form("communication_log", "Patient Communication Log", "ADDITIONAL", [
    sel("Contact type", ["Phone — outgoing", "Phone — incoming", "Portal message", "In person", "Fax", "Email"], req),
    t("Contact with", half),
    t("Regarding", half),
    ta("Communication", req),
    yn("Follow-up needed", half),
  ]),
  form("physical_exam_systems", "Physical Exam (by system)", "ADDITIONAL", [
    cb1("Patient not eligible for Lower Extremity Neurological Exam"),
    ta("Constitutional", {
      help: "Normal: Vital Signs reviewed and within normal limits. The pulse has a regular rate and rhythm. The patient is normotensive. The respiratory rate is regular and non labored. The patient is afebrile. The patient is clean, well groomed and no signs of distress.",
    }),
    ta("Eyes"),
    ta("Ears, Nose, Mouth and Throat"),
    ta("Respiratory"),
    ta("Cardiovascular"),
    ta("Gastrointestinal (GI)"),
    ta("Integumentary (Hair, Skin)", { help: "Wound locations and types, discoloration, induration" }),
    ta("Musculoskeletal"),
    ta("Neurological"),
    ta("Lower Extremity Neurological Exam"),
    ta("Psychiatric"),
    ta("Other findings"),
  ]),
  form("plan_of_care", "Plan Of Care", "ADDITIONAL", [
    n("Weeks in treatment", "weeks", half),
    note("Tick each statement that applies. A ticked statement takes a comment, a plan of care status and the date of that status."),
    care("Actigraft Education", [
      "Patient's wound site has been present for greater than 4 weeks without significant or measurable improvement. We have discussed at length the need to consider actigraft in order to obtain the most optimal long term results. Understanding and agreement verbalized by patient.",
      "We will plan to re-apply on a weekly basis. Clinical evaluation will be made to determine if future applications are medically necessary as an adjunct therapy to standard wound care for further wound healing progression.",
      "Provided and reviewed educational material concerning the use, risks and benefits of Actigraft.",
    ]),
    care("Cellular Tissue Product Education", [
      "Patient's wound site has been present for greater than 4 weeks without significant or measurable improvement. We have discussed at length the need to consider advanced biologic modalities in order to obtain the most optimal long term results. Understanding and agreement verbalized by patient.",
      "We will plan to re-apply the cellular tissue product on a weekly basis. Clinical evaluation will be made to determine if future applications are medically necessary as an adjunct therapy to standard wound care for further wound healing progression.",
      "Provided and reviewed educational material concerning the use, risks and benefits of a cellular tissue product.",
    ]),
    care("Compliance with Treatment Education", ["Importance of compliance with treatment plan in wound healing discussed at length today. Patient and/or caregiver verbalized understanding."]),
    care("Debridement", [
      "Discussed the importance of debridement in the wound healing process and why it is being used as part of the treatment plan.",
      "Discussed the importance of utilizing ultramist as a form of debridement in the wound healing process and why it is being used as part of the treatment plan.",
      "Provided and reviewed educational material concerning the use, risks and benefits of low-frequency, non-contact, non-thermal ultrasound.",
    ]),
    care("Diabetes Education", [
      "Time was taken to discuss common wound specific diabetic complications, as well as preventative measures with patient today at length. Discussed importance of close monitoring and proper blood sugar control in preventing such complications.",
    ]),
    care("Diabetic Foot Education", [
      "Discussed at length common lower extremity diabetic complications and preventative measures. Discussed importance to monitor feet closely and contact our office if any concerns arise.",
    ]),
    care("Edema Management", [
      "Patient was educated on edema management and proper skin care. Discussed importance of elevating lower extremities throughout the day when resting at home. Discussed importance of monitoring dietary sodium intake daily.",
      "Patient with Lymphedema and will benefit from Compression Therapy to reduce edema, increase lymph drainage and promote skin integrity. Discussed treatment plan for Lymphedema including a course of compression therapy twice weekly for a period of 2 to 4 weeks.",
      "Discussed possible need for Lymphedema pumps today if minimal improvement is seen after conservative 4 weeks course of therapy, including compression, exercise and elevation.",
      "Time was taken to discuss and demonstrate the importance of compliance with compression and the role it plays in controlling edema.",
    ]),
    care("Fall Risk", [
      "Inform patient and family of high risk of falling and discuss prevention strategies.",
      "Keep the bed/chair in low position with wheels locked at all times.",
      "Monitor Blood Pressure and Blood Glucose.",
      "Educate patient to get up slowly from lying to sitting / pause / dangle / pause / ambulate.",
      "Encourage exercise, strength-training, and balance enhancing activities to patient's level of tolerance.",
      "Use assistive devices in good operating condition as needed to enhance mobility.",
      "Modify environment to decrease risk of falls.",
    ]),
    care("Negative Pressure Wound Therapy", [
      "Education was provided to patient and/or caregiver regarding negative pressure wound therapy",
      "Patient and/or caregiver verbalized understanding of negative pressure wound therapy",
    ]),
    care("Nutrition Education", [
      "Education and counseling was provided to the patient on the importance of a balanced diet in the patient's overall health and wound healing.",
      "Recommend increased protein intake to aid with wound healing.",
      "Recommend supplementation discussed such as Vitamin A, Vitamin B12, Vitamin C, Vitamin D, Vitamin E, Zinc, L-Arginine, L-Glutamine to aid with wound healing.",
    ]),
    care("Offloading / Pressure Relief", ["Importance of offloading and pressure redistribution in wound healing discussed with patient and/or caregiver."]),
    care("Pressure Ulcer Education", [
      "Pressure Ulcer education was assessed and time was taken to discuss essential measures to prevent complications such as bed shifting throughout the day and proper offloading of at-risk areas at all times.",
    ]),
    care("Smoking/Nicotine Cessation", [
      "Patient is a non-smoker and does not use nicotine.",
      "Educated and counseled the patient on smoking and nicotine cessation and the role it plays in wound healing.",
      "Patient has refrained from smoking and nicotine use for at least 6 weeks and continues to be compliant.",
      "Patient remains non-compliant, despite counseling and educating the patient on smoking and nicotine cessation. Will continue to educate.",
    ]),
    care("Venous Leg Ulcer", [
      "Wound description: venous ulcers are chronic wounds that occur due to poor blood circulation, typically caused by venous insufficiency. They form when leg veins are damaged or inefficient at pumping blood back to the heart, leading to blood pooling in the legs, swelling and ulcer formation from the pressure build-up. They tend to appear as shallow sores with red bases, uneven borders, and shiny, tight, warm or discolored periwound skin.",
      "Common locations: lower legs, between the knee and the ankle. Staging — partial thickness: loss of epidermis and dermis only; full thickness: tissue loss extending into subcutaneous tissue, adipose, bone, tendon or muscle; unstageable: wound bed covered in eschar/slough, unable to visualize the wound base.",
    ]),
    care("Wound Care", [
      "Will impliment and follow standard wound care to include: appropriate serial debridement, offloading when needed, edema control, mitigating and resolving potential and/or current infections, vascular status assessment when needed, product use to promote a wound healing environment, monitoring of patient's nutrition status and coordination with other health care providers who are managing other aspects of the patient's overall health, which contributes to the wound healing process.",
      "Patient's wound plan of care reviewed today. We discussed current regimen and recommendations in order to obtain the most optimal long term results. Understanding and agreement verbalized by patient and/or family / caregiver.",
      "Current wound(s) status documented in the EHR. Assessment and treatment performed today and updated orders discussed.",
      "Discussed and demonstrated the proper application and importance of utilizing the dressings needed to maintain a moist wound environment to promote healing.",
      "Discussed the importance of compliance with the prescribed medication(s) being utilized for wound healing and comorbidity management.",
    ]),
    h("Surveillance goals"),
    sel("Surveillance goals", ["Wound healing", "Wound stabilization / maintenance", "Infection prevention", "Pain and symptom control (palliative)", "Prevention of new wounds", "Not applicable"]),
    h("Treatment plan"),
    sel("Conservative Wound Care", ["Not applicable", "Initiated", "Continued", "Completed", "Discontinued"], half),
    sel("Moderate Wound Care", ["Not applicable", "Initiated", "Continued", "Completed", "Discontinued"], half),
    sel("Advanced Wound Care", ["Not applicable", "Initiated", "Continued", "Completed", "Discontinued"], half),
    h("Data reviewed"),
    ta("Reviewed wound nurse measurements/photos from home visit dated"),
    ta("Reviewed prior encounter notes or external records (source & date)"),
    ta("Reviewed labs or imaging (specify)"),
    ta("Independent interpretation of a test/image performed by me (not just acknowledged)"),
    ta("Discussed case with HHA RN / PCP / specialist / caregiver / pharmacy (who & what)"),
    h("Risk of deterioration"),
    sel("Risk of deterioration", ["Low", "Moderate", "High"], half),
    sel("Frequency of visits", ["Weekly", "Twice weekly", "Every 2 weeks", "Monthly"], half),
    ta("Notes"),
  ]),
  form("pneumatic_compression", "Pneumatic Compression Module", "ADDITIONAL", [
    t("Device", half),
    sel("Limb", ["Right leg", "Left leg", "Both legs", "Right arm", "Left arm"], half),
    n("Pressure", "mmHg", half),
    n("Session length", "minutes", half),
    sel("Frequency", ["Once daily", "Twice daily", "3x per week"], half),
    cbs("Qualifying criteria", ["4 weeks conservative therapy failed", "Chronic venous insufficiency with ulcers", "Lymphedema"]),
    ta("Notes"),
  ]),
  form("braden", "Pressure Ulcer Risk Assessment (Braden)", "ADDITIONAL", [
    rad("Sensory perception", ["Completely limited|1", "Very limited|2", "Slightly limited|3", "No impairment|4"], req),
    rad("Moisture", ["Constantly moist|1", "Very moist|2", "Occasionally moist|3", "Rarely moist|4"], req),
    rad("Activity", ["Bedfast|1", "Chairfast|2", "Walks occasionally|3", "Walks frequently|4"], req),
    rad("Mobility", ["Completely immobile|1", "Very limited|2", "Slightly limited|3", "No limitation|4"], req),
    rad("Nutrition", ["Very poor|1", "Probably inadequate|2", "Adequate|3", "Excellent|4"], req),
    rad("Friction & shear", ["Problem|1", "Potential problem|2", "No apparent problem|3"], req),
    score("Braden score", ["9|Very high risk", "12|High risk", "14|Moderate risk", "18|Mild risk", "23|No risk"]),
    ta("Prevention plan"),
  ]),
  form("pcm", "Principal Care Management", "ADDITIONAL", [
    t("Principal chronic condition", req),
    n("Time this month", "minutes", half),
    sel("Performed by", ["Physician / QHP", "Clinical staff"], half),
    cbs("Activities", ["Care plan review", "Medication management", "Care coordination", "Patient education", "Test follow-up"]),
    yn("Verbal consent documented", half),
    ta("Notes"),
  ]),
  form("recap", "RECAP Documentation", "ADDITIONAL", [
    ta("Reason for visit", req),
    ta("Evaluation"),
    ta("Care provided"),
    ta("Assessment of progress"),
    ta("Plan / next steps"),
  ]),
  form("ros", "Review of Systems", "ADDITIONAL", [
    cbs("Information obtained from", ["Patient", "Chart", "Family", "Caregiver", "Facility staff"], req),
    ...rosSystem("Constitutional Symptoms (General Health)", ["Weakness", "Chills", "Fatigue", "Fever", "Loss of appetite", "Weight change"]),
    ...rosSystem("Eyes", ["Vision changes", "Glasses / contacts"]),
    ...rosSystem("Ear / Nose / Mouth / Throat", ["Hearing loss", "Difficulty swallowing"]),
    ...rosSystem("Respiratory", ["Shortness of breath", "Cough", "Oxygen use"]),
    ...rosSystem("Cardiovascular (Central/Peripheral)", ["Edema", "Lower extremity (leg) swelling", "Chest Pain", "Claudication"]),
    ...rosSystem("Gastrointestinal (GI)", ["Acid Reflux", "Constipation", "Nausea / Vomiting / Diarrhea (N/V/D)", "Bowel incontinence"]),
    ...rosSystem("Genitourinary (GU)", ["Urinary Incontinence", "Urinary frequency / burning", "Catheter"]),
    ...rosSystem("Endocrine", ["Diabetes — blood sugar not controlled", "Excessive thirst"]),
    ...rosSystem("Hematologic / Lymphatic", ["Bleeding / bruising easily", "On blood thinners"]),
    ...rosSystem("Integumentary (Hair/Skin/Nails)", ["Change: Hair, Nails, Skin", "Ulcers", "Rash / itching"]),
    ...rosSystem("Musculoskeletal", ["Assistive Devices", "Muscle Weakness", "Joint pain"]),
    ...rosSystem("Neurological", ["Memory Loss", "One-sided weakness", "Pain from Neuropathy", "Numbness / tingling"]),
    ...rosSystem("Psychiatric", ["Anxiety", "Depression"]),
    ta("Details", { help: "Anything to add to a finding, e.g. Urinary Incontinence - urinary incontinent" }),
  ]),
  form("social_history", "Social History", "ADDITIONAL", [
    sel("Tobacco", ["Never", "Former", "Current every day", "Current some days"], half),
    sel("Alcohol", ["None", "Social", "Daily"], half),
    sel("Living situation", ["Home alone", "Home with family", "Assisted living", "Skilled nursing facility", "Homeless"], half),
    sel("Ambulation", ["Independent", "Cane / walker", "Wheelchair", "Bedbound"], half),
    ta("Notes"),
  ]),
  form("surgical_history", "Surgical History", "ADDITIONAL", [ta("Surgeries (procedure — year)", req), yn("Prior amputation", half), yn("Prior vascular surgery", half)]),
  form("telehealth_plans", "Telehealth Treatment Plans", "ADDITIONAL", [ta("Treatment plan", req), sel("Telehealth frequency", ["Weekly", "Every 2 weeks", "Monthly"], half), yn("In-person visit needed", half)]),
  form(
    "telemedicine_consent",
    "Telemedicine Consent",
    "ADDITIONAL",
    [
      note("These questions are verbally asked to gain the patient's consent for the telemedicine visit."),
      rad("I consent to engage in a virtual check-in with my healthcare provider.", ["Yes", "No"], req),
      rad("I understand there are potential risks to the use of technology in this virtual check-in, including interruptions and/or interception of my information by an unauthorized party.", ["Yes", "No"], req),
      rad("I agree to not hold my provider responsible for any claims, damages, or expenses that may arise from technical issues during the session, including any costs related to legal or investigative actions.", ["Yes", "No"], req),
      rad("I consent to have this telehealth appointment recorded for review and documentation purposes of my healthcare provider.", ["Yes", "No"], req),
      ta("Notes"),
    ],
    { critical: true }
  ),
  form("telemedicine_visit", "Telemedicine Visit", "ADDITIONAL", [
    sel("Modality", ["Audio & video", "Audio only"], req),
    t("Platform", half),
    t("Patient location", half),
    t("Provider location", half),
    n("Visit length", "minutes", half),
    t("Others present", half),
    ta("Visit note"),
  ]),
  form("visit_discharge_info", "Visit Discharge Information", "ADDITIONAL", [
    sel("Discharged to", ["Home", "Home with home health", "Skilled nursing facility", "Hospital", "Hospice"], req),
    sel("Condition", ["Stable", "Improved", "Unchanged", "Declined"], half),
    t("Accompanied by", half),
    ta("Notes"),
  ]),
  form(
    "debridement",
    "Debridement",
    "PROCEDURE",
    [
      t("Performed by", half),
      sel("Debridement", ["Selective", "Excisional — subcutaneous tissue", "Excisional — muscle / fascia", "Excisional — bone", "Mechanical", "Enzymatic", "Autolytic", "Ultrasound"], { ...req, width: "half" }),
      yn("Time-out taken", half),
      t("Pain control", { ...half, help: "e.g. 5% Lido" }),
      h("Post debridement measurements"),
      n("Length", "cm", half),
      n("Width", "cm", half),
      n("Depth", "cm", half),
      n("Area", "cm²", half),
      n("Percent debrided", "%", half),
      n("Total area debrided", "sq cm", half),
      n("Volume", "cm³", half),
      h("Procedure"),
      cbs("Devitalized tissue debrided", ["Biofilm", "Exudate", "Slough", "Eschar", "Fibrin", "Callus", "Necrotic tissue", "Subcutaneous tissue", "Muscle / fascia", "Bone"], req),
      cbs("Instrument", ["Curette", "Scalpel", "Forceps", "Scissors", "Other"]),
      sel("Bleeding", ["None", "Minimal", "Moderate", "Heavy"], half),
      sel("Hemostasis achieved", ["Pressure", "Silver nitrate", "Electrocautery", "Not required"], half),
      sel("Procedural pain", PAIN_0_10, half),
      sel("Post procedural pain", PAIN_0_10, half),
      sel("Response to treatment", TREATMENT_RESPONSE),
      cbs("Medical necessity statement", [
        "This wound has necrotic tissue and biofilm present that will impede continued wound healing. The debridement of the nonviable tissue and biofilm creating a clean wound bed is medically necessary to promote wound healing.",
      ]),
      ta("Notes"),
    ],
    { perWound: true, signatureRequired: true }
  ),
  form(
    "unna_boot",
    "Unna Boot Application",
    "PROCEDURE",
    [
      t("Performed by", half),
      sel("Limb", ["Left Leg", "Right Leg", "Both legs"], half),
      sel("Procedural pain", PAIN_0_10, half),
      sel("Post procedural pain", PAIN_0_10, half),
      sel("Response to treatment", TREATMENT_RESPONSE),
      ta("Notes"),
    ],
    { perWound: true }
  ),
  form(
    "wound_assessment_details",
    "Wound Assessment Details",
    "ADDITIONAL",
    [
      h("Wound status"),
      sel("Wound condition", ["Acute", "Chronic"], half),
      sel("Wound status", ["Not Healed", "Healed", "Converted", "Amputated", "Closed surgically"], half),
      yn("Acquired at facility", half),
      t("Unit acquired", half),
      yn("Recurrence of previously resolved wound", half),
      yn("Is the patient's wound a direct result of an accident?", half),
      d("Date of accident", half),
      t("Responsible party", half),
      sel("Avoidable wound", ["Avoidable", "Unavoidable", "Not determined"], half),
      d("Date of resolution", half),
      ta("Wound notes"),
      h("Wound description"),
      sel("Wound encounter", ["Initial", "Subsequent"], half),
      sel("Wound progress", ["Improving", "Not changed", "Deteriorating", "Healed"], half),
      sel("Thickness", ["Partial Thickness", "Full Thickness", "Unstageable", "Deep tissue injury"], half),
      sel("Wound margin", ["Attached to Wound Base", "Not attached", "Rolled (epibole)", "Macerated", "Callused", "Undefined"], half),
      cb1("No measurable depth"),
      cb1("Patient is not eligible for pain assessment"),
      t("Tunneling", half),
      t("Undermining", half),
      t("Sinus tract", half),
      cbs("Granulation color", ["Pale Grey", "Bright Red", "Pink"], half),
      h("Exposed structure"),
      yn("Limited to breakdown of skin", half),
      cbs("Exposed", ["Adipose", "Muscle", "Tendon", "Capsule", "Joint", "Bone"], half),
      cbs("Exposed with necrosis", ["Adipose", "Muscle", "Tendon", "Capsule", "Joint", "Bone"], half),
      yn("Suspected osteomyelitis", half),
      h("Periwound skin appearance"),
      cbs("Texture", ["Brawny Induration", "Edema", "Excoriation", "Induration", "Callus", "Crepitus", "Fluctuance", "Friable", "Rash", "Scar Tissue", "Shiny", "Denuded"], half),
      cbs("Color", ["Atrophe Blanche", "Cyanosis", "Ecchymosis", "Erythema", "Hemosiderin Staining", "Pallor", "Rubor"], half),
      sel("Moisture", ["Normal For Patient", "Dry / Scaly", "Maceration"], half),
      sel("Temperature", ["Warm", "Cool", "Hot", "No Abnormality"], half),
      yn("Signs / symptoms of infection present", half),
      h("Patient adherence"),
      yn("General non-compliance", half),
      cbs("Compliant with", ["Compression", "Diet", "Dressing Changes", "Exercise", "Limb Elevation", "Medication", "Off-Loading / Protection", "Smoking Cessation", "Wound Visits", "HBO Visits"]),
      t("Other adherence notes"),
      h("Offloading compliance"),
      sel("Patient continues to be compliant with offloading with the use of the following offloading device", OFFLOADING_DEVICES),
    ],
    { perWound: true }
  ),
  form("treatment_goals", "Treatment Goals", "ADDITIONAL", [
    h("Wound healing potential and chronic contributing conditions"),
    sel("Assessment", [
      "The patient's wound(s) have a high potential to heal with no complications.",
      "The patient's wound(s) have a moderate potential to heal; contributing conditions are being managed.",
      "The patient's wound(s) have a low potential to heal; goals are palliative / maintenance.",
    ], req),
    h("Education / understanding"),
    cbs("Patient / caregiver understanding", [
      "has understanding of treatment plan and how to care for wound(s).",
      "has skills necessary to maintain the individual plan of care.",
      "has the knowledge to be able to identify potential signs & symptoms that can impede wound healing.",
      "understands the need for continued care when health problems are identified.",
      "has the knowledge of risk factors and interventions to address.",
    ]),
    h("Clinical goals"),
    cbs("Clinical goals", ["Prevention of infection.", "Edema Control.", "Wound Closure.", "Pain control.", "Offloading / pressure relief.", "Maintenance / palliative care."], req),
    h("Wound healing timeline"),
    sel("Complete wound(s) healing is expected to be within", ["4 weeks", "8 weeks", "12 weeks", "16 weeks", "More than 16 weeks", "Not expected to heal"], half),
  ]),
  form("scribe_statement", "Scribe Statement", "ADDITIONAL", [
    t("This encounter was scribed by the following personnel", req),
    t("The scribe listed above scribed for the following provider", req),
  ]),
  form("vitals_additional", "Vital Signs — Blood Glucose & Oxygen", "ADDITIONAL", [
    n("Blood glucose", "mg/dl", half),
    t("Reference range", { ...half, help: "e.g. 60-110 mg/dl" }),
    n("Inhaled oxygen concentration", "L/min", half),
    n("Inhaled oxygen concentration (FiO2)", "%", half),
  ]),
  form(
    "wound_management_plan",
    "Wound Management Plan",
    "ADDITIONAL",
    [
      ta("Goals for this wound", req),
      cbs("Plan", ["Continue current treatment", "Change dressing", "Debridement", "Advanced modality", "Refer to vascular", "Refer to podiatry", "Refer to infectious disease"]),
      sel("Healing trajectory", ["Improving", "Stalled", "Deteriorating", "Healed"], half),
      d("Target heal date", half),
    ],
    { perWound: true }
  ),
  form("wound_product_supplier", "Wound Product Supplier", "ADDITIONAL", [
    t("Supplier", req),
    t("Supplier phone", half),
    t("Order number", half),
    cbs("Products ordered", WOUND_PRODUCTS),
    n("Quantity (days supply)", "days", half),
    d("Order date", half),
    ta("Notes"),
  ]),

  // ---------------- Hyperbaric oxygen (wound pack) ----------------
  form(
    "hbo_pretreatment",
    "HBO Pretreatment Checklist",
    "DOCUMENTATION",
    [
      h("Indication & authorization"),
      sel("Approved indication", HBO_INDICATIONS, req),
      t("Treatment number (of planned)", half),
      t("Authorization number", half),
      d("Authorization through", half),
      n("Treatments authorized", undefined, half),
      yn("Physician treatment order on file for today", half),
      yn("Consent signed", half),
      h("Pre-dive assessment"),
      n("Blood glucose (diabetic patients)", "mg/dL", half),
      yn("Glucose checked within 1 hour (diabetic)", half),
      n("Temperature", "°F", half),
      n("Heart rate", "bpm", half),
      t("Blood pressure", half),
      n("SpO2", "%", half),
      yn("Lungs clear on auscultation", half),
      yn("Ears clear — able to equalise (otoscopy done)", half),
      yn("Fever, cold or sinus congestion today", half),
      yn("Claustrophobia or anxiety today", half),
      yn("Medications reviewed (steroids, chemotherapy, disulfiram)", half),
      yn("Pregnancy ruled out (where applicable)", half),
      ta("Concerns — physician notified"),
      sel("Cleared to treat", ["Yes", "No — treatment held", "Physician to decide"], req),
    ],
    { description: "Assessment before each hyperbaric treatment.", signatureRequired: true }
  ),
  form(
    "hbo_safety",
    "HBO Safety Checklist",
    "DOCUMENTATION",
    [
      note("Go/no-go safety check before pressurisation. Any item not met: do not treat."),
      cbs("Patient", ["100% cotton gown — no synthetics", "No petroleum, oil or alcohol based products (lotion, hair products, make-up, nail polish)", "No lighters, matches, electronics, watches, hearing aids, jewellery", "No hand/foot warmers or heating devices", "Dressings checked — no petrolatum/ointment exposed", "Grounding strap applied", "Patient briefed: equalising, air breaks, signals", "Water available in approved container"]),
      cbs("Chamber & equipment", ["Chamber inspected, acrylic free of damage", "Fire suppression / deluge checked", "Oxygen supply and pressure adequate", "Communication system tested", "Ground continuity checked", "Humidity within limits", "Emergency equipment in place", "Operator and safety director present"]),
      yn("All items met — safe to pressurise", req),
      t("Chamber operator", half),
      t("Safety director / supervising physician", half),
      ta("Exceptions"),
    ],
    { description: "Fire and safety checklist for each hyperbaric treatment.", signatureRequired: true }
  ),
  form(
    "hbo_treatment",
    "HBO Treatment Record",
    "PROCEDURE",
    [
      h("Treatment"),
      sel("Chamber", ["Monoplace 1", "Monoplace 2", "Monoplace 3", "Multiplace"], half),
      n("Treatment pressure", "ATA", half),
      n("Time at pressure", "min", half),
      n("Descent", "min", half),
      n("Ascent", "min", half),
      n("Air breaks", undefined, half),
      t("Start time", half),
      t("End time", half),
      n("Total treatment time", "min", half),
      h("Monitoring"),
      t("BP before / after", half),
      t("Heart rate before / after", half),
      n("Glucose after (diabetic)", "mg/dL", half),
      n("SpO2 after", "%", half),
      yn("Ears equalised without difficulty", half),
      sel("Patient tolerance", TREATMENT_RESPONSE, half),
      h("Complications"),
      cbs("Events during treatment", ["None", "Ear pain / barotrauma", "Sinus pain", "Claustrophobia / anxiety", "Hypoglycaemia", "Oxygen toxicity symptoms (twitching, nausea, vision change)", "Seizure", "Pneumothorax suspected", "Treatment aborted"]),
      ta("Event details and action taken"),
      h("Billing"),
      sel("Physician attendance", ["Physician present and in attendance throughout (99183)", "Physician immediately available", "Not applicable"], half),
      sel("Facility code", ["G0277 — HBO under pressure, per 30 min interval"], half),
      n("30-minute intervals", undefined, half),
      ta("Treatment note"),
    ],
    { description: "Each hyperbaric session: pressure, times, monitoring, complications and the billing basis (99183 / G0277).", signatureRequired: true }
  ),
  form(
    "tcom",
    "Transcutaneous Oximetry (TCOM)",
    "PROCEDURE",
    [
      note("Transcutaneous oxygen pressure (TcPO2). Values under 40 mmHg suggest impaired healing; the oxygen challenge predicts HBO benefit."),
      sel("Indication", ["HBO candidacy", "Healing potential of a wound", "Amputation level", "Post-revascularisation"], req),
      h("Electrode sites (mmHg, room air)"),
      n("Reference site — chest", "mmHg", half),
      n("Site 1 (periwound)", "mmHg", half),
      t("Site 1 location", half),
      n("Site 2", "mmHg", half),
      t("Site 2 location", half),
      n("Site 3", "mmHg", half),
      t("Site 3 location", half),
      n("Site 4", "mmHg", half),
      t("Site 4 location", half),
      h("Challenges"),
      n("Site 1 on 100% oxygen", "mmHg", half),
      n("Site 1 with leg elevation", "mmHg", half),
      n("Site 1 at pressure (in-chamber, if done)", "mmHg", half),
      n("Regional perfusion index (site / reference)", undefined, half),
      h("Interpretation"),
      sel("Baseline periwound TcPO2", ["> 40 mmHg — adequate", "30–40 mmHg — borderline", "< 30 mmHg — impaired", "< 20 mmHg — severe hypoxia"], half),
      sel("Oxygen challenge response", ["Rises above 200 mmHg — likely to benefit from HBO", "Rises 50–200 mmHg — possible benefit", "Minimal rise — unlikely to benefit; vascular evaluation", "Not done"], half),
      ta("Interpretation and plan"),
    ],
    { description: "TcPO2 measurements with oxygen challenge (94760 / 93922 not applicable — use CPT per practice).", signatureRequired: true }
  ),
  // ---------------- Primary-care pack ----------------
  form(
    "phq9",
    "Depression Screening (PHQ-9)",
    "ADDITIONAL",
    [
      note("Over the last 2 weeks, how often have you been bothered by any of the following problems?"),
      ...PHQ9_ITEMS.map((q) => rad(q, FREQ_0_3, req)),
      score("PHQ-9 total", ["4|Minimal", "9|Mild", "14|Moderate", "19|Moderately severe", "27|Severe"]),
      rad("If any problems: how difficult have they made it to do your work, take care of things at home, or get along with people?", ["Not difficult at all", "Somewhat difficult", "Very difficult", "Extremely difficult"]),
      yn("Item 9 (thoughts of self-harm) positive — safety assessment done", half),
      sel("Plan", ["No action — rescreen in a year", "Monitor — rescreen in 1–3 months", "Counselling / behavioural health referral", "Start or adjust medication", "Urgent safety plan / crisis referral"], half),
      ta("Notes"),
    ],
    { description: "Patient Health Questionnaire-9; satisfies the yearly depression screening rule." }
  ),
  form(
    "gad7",
    "Anxiety Screening (GAD-7)",
    "ADDITIONAL",
    [
      note("Over the last 2 weeks, how often have you been bothered by the following problems?"),
      ...GAD7_ITEMS.map((q) => rad(q, FREQ_0_3, req)),
      score("GAD-7 total", ["4|Minimal", "9|Mild", "14|Moderate", "21|Severe"]),
      sel("Plan", ["No action", "Monitor — rescreen in 1–3 months", "Counselling / behavioural health referral", "Start or adjust medication"], half),
      ta("Notes"),
    ],
    { description: "Generalized Anxiety Disorder 7-item scale." }
  ),
  form(
    "audit_c",
    "Alcohol Use Screening (AUDIT-C)",
    "ADDITIONAL",
    [
      rad("How often do you have a drink containing alcohol?", ["Never|0", "Monthly or less|1", "2–4 times a month|2", "2–3 times a week|3", "4 or more times a week|4"], req),
      rad("How many drinks do you have on a typical day when you are drinking?", ["1 or 2|0", "3 or 4|1", "5 or 6|2", "7 to 9|3", "10 or more|4"], req),
      rad("How often do you have six or more drinks on one occasion?", ["Never|0", "Less than monthly|1", "Monthly|2", "Weekly|3", "Daily or almost daily|4"], req),
      score("AUDIT-C total", ["2|Negative", "3|Positive for women (3+)", "12|Positive (4+ men, 3+ women)"]),
      sel("Plan", ["No action", "Brief intervention / advice given", "Referral for alcohol use treatment"], half),
      ta("Notes"),
    ],
    { description: "Three-question alcohol screen; satisfies the yearly alcohol screening rule." }
  ),
  form(
    "awv_hra",
    "Annual Wellness Visit — Health Risk Assessment",
    "DOCUMENTATION",
    [
      h("Visit"),
      rad("Visit type", ["Initial AWV (G0438)", "Subsequent AWV (G0439)", "Welcome to Medicare (G0402)"], req),
      yn("Health risk assessment completed by patient (or caregiver) before the visit", half),
      h("Self-assessment"),
      rad("Overall health", ["Excellent", "Very good", "Good", "Fair", "Poor"], half),
      rad("Psychosocial: feels down, depressed or hopeless (last 2 weeks)", ["Not at all", "Several days", "More than half the days", "Nearly every day"], half),
      rad("Feels lonely or isolated", ["Never", "Sometimes", "Often"], half),
      sel("Physical activity (minutes of moderate activity a week)", ["None", "Under 60", "60–149", "150 or more"], half),
      cbs("Behavioural risks", ["Tobacco use", "Alcohol above limits", "Other substance use", "No seat belt", "Firearm in home, unsecured", "Sun exposure without protection"]),
      h("Functional ability & safety"),
      cbs("Needs help with (ADLs)", ["Bathing", "Dressing", "Toileting", "Transferring", "Eating", "Walking"]),
      cbs("Needs help with (IADLs)", ["Shopping", "Cooking", "Housework", "Medications", "Finances", "Transportation", "Telephone"]),
      yn("Fallen in the past year", half),
      yn("Afraid of falling", half),
      yn("Hearing difficulty", half),
      yn("Vision difficulty", half),
      yn("Home safety concerns (stairs, lighting, grab bars, rugs)", half),
      yn("Bladder or bowel control problems", half),
      h("Cognition"),
      rad("Cognitive screen", ["Mini-Cog — normal", "Mini-Cog — positive, refer", "MoCA done (see score)", "Not done"], half),
      n("Cognitive screen score", undefined, half),
      yn("Family or caregiver concerned about memory", half),
      h("Advance care planning"),
      yn("Advance directive on file", half),
      yn("Health care proxy named", half),
      yn("Advance care planning discussed today (99497)", half),
      h("Providers, medications & history reviewed"),
      ta("Other providers and suppliers involved in care"),
      yn("Medication list reviewed and reconciled", half),
      yn("Family history reviewed", half),
      yn("Medical and surgical history reviewed", half),
      h("Personalised prevention plan"),
      cbs("Screenings and immunizations due (see care gaps)", ["Colorectal cancer", "Breast cancer", "Cervical cancer", "Lung cancer (if eligible)", "Osteoporosis (DEXA)", "AAA ultrasound", "Lipids", "Diabetes", "Hepatitis C", "HIV", "Influenza", "Pneumococcal", "Shingles", "Tdap", "COVID-19"]),
      cbs("Referrals and counselling", ["Nutrition", "Physical activity", "Tobacco cessation", "Fall prevention / PT", "Behavioural health", "Social work / community resources", "Audiology", "Ophthalmology / optometry"]),
      ta("Written screening schedule given to patient (5–10 year plan)"),
      ta("Risk factors and conditions identified, with plan"),
    ],
    { description: "Medicare AWV with the health risk assessment, functional and cognitive screen and the personalised prevention plan.", signatureRequired: true }
  ),
  form(
    "preventive_care",
    "Preventive Care Checklist",
    "ADDITIONAL",
    [
      note("Tick what was reviewed today; dates of the last one and what was ordered. Care-gap alerts on the chart list what is due."),
      h("Cancer screening"),
      ...screening("Colorectal (45–75: FIT yearly / colonoscopy 10 yr)"),
      ...screening("Breast — mammogram (women 40–74, 2 yr)"),
      ...screening("Cervical — Pap / HPV (women 21–65)"),
      ...screening("Lung — low-dose CT (50–80, 20 pack-years, smoked within 15 yr)"),
      ...screening("Prostate — PSA discussed (men 55–69, shared decision)"),
      h("Cardiometabolic"),
      ...screening("Blood pressure"),
      ...screening("Lipid panel"),
      ...screening("Diabetes screen (A1c / glucose)"),
      ...screening("BMI / weight counselling"),
      h("Infectious disease"),
      ...screening("HIV (15–65, once)"),
      ...screening("Hepatitis C (18–79, once)"),
      ...screening("Hepatitis B (at risk)"),
      h("Other"),
      ...screening("Osteoporosis — DEXA (women 65+)"),
      ...screening("AAA ultrasound (men 65–75, ever smoked, once)"),
      ...screening("Depression (PHQ-9)"),
      ...screening("Alcohol use (AUDIT-C)"),
      ...screening("Tobacco use & cessation advice"),
      ...screening("Falls risk (65+)"),
      h("Immunizations"),
      cbs("Up to date", ["Influenza", "COVID-19", "Tdap / Td", "Pneumococcal", "Shingles (RZV)", "Hepatitis B", "HPV (through 26)", "RSV (60+ / 75+)", "MMR / varicella (if no immunity)"]),
      cbs("Given or ordered today", ["Influenza", "COVID-19", "Tdap / Td", "Pneumococcal", "Shingles (RZV)", "Hepatitis B", "HPV", "RSV"]),
      ta("Counselling given / patient declined"),
    ],
    { description: "USPSTF A/B screenings and ACIP immunizations, reviewed at physicals and wellness visits." }
  ),
  form(
    "diabetes_flowsheet",
    "Diabetes Follow-up",
    "DOCUMENTATION",
    [
      h("Control"),
      n("A1c (%)", "%", half),
      d("A1c date", half),
      n("A1c goal (%)", "%", half),
      sel("Glucose log reviewed", ["Not available", "Reviewed — at goal", "Reviewed — above goal", "Reviewed — hypoglycaemia present"], half),
      yn("Hypoglycaemia episodes since last visit", half),
      sel("Self-monitoring / CGM", ["None", "Fingerstick", "CGM"], half),
      h("Yearly measures"),
      d("Urine microalbumin / creatinine — date", half),
      t("Urine microalbumin result", half),
      d("eGFR — date", half),
      n("eGFR", "mL/min", half),
      d("Lipid panel — date", half),
      n("LDL", "mg/dL", half),
      d("Dilated eye exam — date", half),
      sel("Eye exam result", ["No retinopathy", "Retinopathy present", "Not done"], half),
      d("Foot exam — date", half),
      sel("Foot exam", ["Normal", "Loss of protective sensation", "Ulcer / deformity — refer", "Not done"], half),
      yn("Dental visit in the past year", half),
      h("Treatment"),
      cbs("Medications", ["Metformin", "SGLT2 inhibitor", "GLP-1 RA", "DPP-4 inhibitor", "Sulfonylurea", "Basal insulin", "Prandial insulin", "Statin", "ACE inhibitor / ARB", "Aspirin"]),
      yn("Statin indicated and prescribed (40–75)", half),
      yn("ACE/ARB indicated and prescribed (albuminuria / hypertension)", half),
      cbs("Education & referrals", ["Diabetes self-management education", "Nutrition / dietitian", "Exercise plan", "Smoking cessation", "Endocrinology", "Podiatry", "Ophthalmology", "Nephrology"]),
      cbs("Immunizations reviewed", ["Influenza", "Pneumococcal", "Hepatitis B", "COVID-19"]),
      ta("Assessment & plan changes"),
      sel("Follow-up", ["3 months", "6 months", "Sooner — see plan"], half),
    ],
    { description: "ADA standards-of-care flowsheet for a diabetes follow-up visit." }
  ),
  form(
    "hypertension_flowsheet",
    "Hypertension Follow-up",
    "DOCUMENTATION",
    [
      h("Blood pressure"),
      n("Office BP systolic", "mmHg", half),
      n("Office BP diastolic", "mmHg", half),
      n("Repeat / average systolic", "mmHg", half),
      n("Repeat / average diastolic", "mmHg", half),
      sel("Home BP log", ["Not available", "Reviewed — at goal", "Reviewed — above goal"], half),
      sel("Goal", ["< 130/80", "< 140/90", "Individualised (see plan)"], half),
      rad("At goal today", ["Yes", "No"], half),
      h("Risk & target organs"),
      cbs("Comorbidities", ["Diabetes", "CKD", "Coronary disease", "Heart failure", "Stroke / TIA", "Atrial fibrillation", "Sleep apnoea", "Obesity"]),
      n("Last eGFR", "mL/min", half),
      d("Last BMP / eGFR date", half),
      d("Last lipid panel", half),
      d("Last ECG", half),
      n("10-year ASCVD risk (%)", "%", half),
      h("Treatment & lifestyle"),
      cbs("Antihypertensives", ["ACE inhibitor", "ARB", "Thiazide diuretic", "Calcium channel blocker", "Beta blocker", "Spironolactone", "Other"]),
      sel("Adherence", ["Taking as prescribed", "Misses doses", "Stopped — side effects", "Stopped — cost"], half),
      cbs("Lifestyle counselling", ["Sodium < 1.5–2.3 g/day", "DASH diet", "Weight loss", "Physical activity 150 min/week", "Limit alcohol", "Tobacco cessation"]),
      sel("Medication change today", ["None", "Dose increased", "Agent added", "Agent changed", "Dose reduced"], half),
      ta("Assessment & plan"),
      sel("Follow-up", ["2–4 weeks (not at goal)", "3 months", "6 months"], half),
    ],
    { description: "ACC/AHA hypertension follow-up flowsheet." }
  ),
  form(
    "asthma_control",
    "Asthma / COPD Control (ACT)",
    "DOCUMENTATION",
    [
      note("Asthma Control Test — past 4 weeks. Score 19 or less = not well controlled."),
      rad("How much of the time did your asthma keep you from getting as much done at work, school or home?", ["All of the time|1", "Most of the time|2", "Some of the time|3", "A little of the time|4", "None of the time|5"], req),
      rad("How often have you had shortness of breath?", ["More than once a day|1", "Once a day|2", "3 to 6 times a week|3", "Once or twice a week|4", "Not at all|5"], req),
      rad("How often did symptoms wake you up at night or earlier than usual?", ["4 or more nights a week|1", "2 or 3 nights a week|2", "Once a week|3", "Once or twice|4", "Not at all|5"], req),
      rad("How often have you used your rescue inhaler or nebuliser?", ["3 or more times a day|1", "1 or 2 times a day|2", "2 or 3 times a week|3", "Once a week or less|4", "Not at all|5"], req),
      rad("How would you rate your asthma control?", ["Not controlled at all|1", "Poorly controlled|2", "Somewhat controlled|3", "Well controlled|4", "Completely controlled|5"], req),
      score("ACT score", ["15|Very poorly controlled", "19|Not well controlled", "25|Well controlled"]),
      h("Assessment"),
      n("Peak flow / FEV1 (% predicted)", "%", half),
      n("SpO2", "%", half),
      sel("Exacerbations since last visit (oral steroids, ED, admission)", ["None", "1", "2 or more"], half),
      sel("Inhaler technique", ["Checked — correct", "Checked — corrected today", "Not checked"], half),
      cbs("Triggers reviewed", ["Tobacco smoke", "Allergens", "Exercise", "Viral infections", "Occupational", "GERD", "Weather"]),
      cbs("Controller therapy", ["ICS", "ICS/LABA", "LAMA", "LTRA", "Biologic", "None"]),
      sel("Step change", ["No change", "Step up", "Step down"], half),
      yn("Written asthma action plan given / updated", half),
      cbs("Immunizations reviewed", ["Influenza", "Pneumococcal", "COVID-19", "RSV"]),
      ta("Assessment & plan"),
    ],
    { description: "Asthma Control Test with the follow-up assessment; also used for COPD visits." }
  ),
  form(
    "well_child",
    "Well-Child Visit",
    "DOCUMENTATION",
    [
      h("Visit"),
      sel("Age visit", ["Newborn", "1 month", "2 months", "4 months", "6 months", "9 months", "12 months", "15 months", "18 months", "24 months", "30 months", "3 years", "4 years", "5 years", "6 years", "7 years", "8 years", "9 years", "10 years", "11 years", "12 years", "13 years", "14 years", "15 years", "16 years", "17 years", "18 years+"], req),
      t("Accompanied by", half),
      h("Growth (plot on the growth chart)"),
      n("Weight", "kg", half),
      n("Length / height", "cm", half),
      n("Head circumference (under 3)", "cm", half),
      n("BMI (2+)", "kg/m²", half),
      t("Weight percentile", half),
      t("Height percentile", half),
      t("BMI percentile", half),
      h("Nutrition & sleep"),
      sel("Feeding", ["Breast", "Formula", "Mixed", "Solids started", "Table food", "Regular diet"], half),
      sel("Sleep", ["Age-appropriate", "Concern — see notes"], half),
      sel("Elimination / toileting", ["Age-appropriate", "Concern — see notes"], half),
      h("Development"),
      rad("Developmental screening (ASQ / PEDS at 9, 18, 30 months)", ["Done — on track", "Done — concern, refer", "Not due", "Not done"]),
      rad("Autism screening (M-CHAT at 18 and 24 months)", ["Done — negative", "Done — positive, refer", "Not due", "Not done"]),
      cbs("Milestones reviewed", ["Gross motor", "Fine motor", "Language", "Social / emotional", "Cognitive"]),
      cbs("Concerns", ["Speech / language", "Motor", "Behaviour", "Social", "Learning / school", "None"]),
      h("Screening"),
      sel("Vision", ["Normal", "Abnormal — refer", "Not done"], half),
      sel("Hearing", ["Normal", "Abnormal — refer", "Not done"], half),
      sel("Lead (12 & 24 months, at risk)", ["Done", "Ordered", "Not due"], half),
      sel("Anaemia (12 months)", ["Done", "Ordered", "Not due"], half),
      sel("Dental / fluoride varnish", ["Applied", "Dentist established", "Referred", "Not due"], half),
      sel("Adolescent: depression screen (12+)", ["Done — negative", "Done — positive", "Not due"], half),
      sel("Adolescent: substance use (CRAFFT)", ["Done — negative", "Done — positive", "Not due"], half),
      h("Immunizations"),
      sel("Immunizations", ["Up to date — given today", "Up to date — none due", "Catch-up given", "Declined", "Deferred"], half),
      ta("Vaccines given today"),
      h("Anticipatory guidance"),
      cbs("Discussed", ["Safe sleep", "Car seat / seat belt", "Nutrition", "Physical activity", "Screen time", "Injury prevention", "Water / sun safety", "Firearm safety", "Discipline / behaviour", "School readiness", "Puberty / sexual health", "Tobacco, alcohol, drugs", "Mental health", "Social media"]),
      ta("Assessment & plan"),
      sel("Next well visit", ["1 month", "2 months", "3 months", "6 months", "1 year"], half),
    ],
    { description: "Bright Futures / AAP periodicity well-child visit." }
  ),
];

// previousSteps: step lists this workflow shipped with before. A practice whose workflow still matches one of
// them never changed it, and takes the current steps; one that edited its workflow keeps its own.
export type CatalogWorkflow = { name: string; description: string; visitTypes: string[]; isDefault?: boolean; steps: [string, boolean][]; previousSteps?: string[][] };

// [template key, required to finalize]
export const STANDARD_WORKFLOWS: CatalogWorkflow[] = [
  {
    name: "Wound Care Visit",
    description: "Provider wound care visit — documentation, procedures, progress note and superbill.",
    visitTypes: ["NEW", "FOLLOW_UP", "SICK", "WELL", "WOUND_CARE", "INIT_WOUND", "EST_WOUND", "SNF_EST", "SURVEILLANCE"],
    isDefault: true,
    steps: [
      ["cc", true],
      ["vitals", false],
      ["wounds", true],
      ["problems", false],
      ["physician_orders", false],
      ["exam", true],
      ["assessment", true],
      ["meds", false],
      ["procedures", false],
      ["treatment_notes", false],
      ["multiwound", false],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  {
    name: "Non-Provider Treatment Visit",
    description: "Clinical staff treatment visit (e.g. ultrasound MIST therapy, dressing change).",
    visitTypes: ["NON_PROVIDER"],
    steps: [
      ["cc", true],
      ["vitals", false],
      ["wounds", true],
      ["treatment_notes", true],
      ["multiwound", false],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  {
    name: "Telehealth Visit",
    description: "Telehealth wound care visit: consent, wounds, HPI, plan of care, problem list, orders, history, review of systems and exam.",
    visitTypes: ["TELE", "TELE_INIT", "TELE_EST"],
    // The order the clinical team charts a telehealth wound care visit in.
    steps: [
      ["telemedicine_consent", true],
      ["telemedicine_visit", true],
      ["wounds", true],
      ["cc", true],
      ["plan_of_care", false],
      ["wound_management_plan", false],
      ["problems", true],
      ["physician_orders", false],
      ["telehealth_plans", false],
      ["assessment", true],
      ["progress", false],
      ["vitals", false],
      ["code_status", false],
      ["treatment_notes", false],
      ["allergy_list", false],
      ["meds", false],
      ["medical_history", false],
      ["surgical_history", false],
      ["family_history", false],
      ["social_history", false],
      ["ros", false],
      ["physical_exam_systems", false],
      ["attestation_statements", false],
      ["superbill", false],
      ["signatures", false],
    ],
    previousSteps: [
      ["telemedicine_consent", "cc", "telemedicine_visit", "wounds", "assessment", "progress", "superbill", "signatures"],
      ["telemedicine_consent", "telemedicine_visit", "wounds", "cc", "plan_of_care", "wound_management_plan", "problems", "physician_orders", "telehealth_plans", "assessment", "progress", "vitals", "treatment_notes", "allergy_list", "meds", "medical_history", "surgical_history", "family_history", "social_history", "ros", "physical_exam_systems", "attestation_statements", "superbill", "signatures"],
    ],
  },
  // The visit types below each chart with their own set of documents, as the clinical team is used to.
  {
    name: "Initial Wound Care",
    description: "First provider wound care visit: full history, exam, risk assessments, plan of care and orders.",
    visitTypes: ["INIT_WOUND", "NEW"],
    steps: [
      ["wounds", true], ["problems", true], ["procedures", false], ["physician_orders", false], ["meds", false], ["cc", true], ["vitals", false], ["code_status", false],
      ["allergy_list", false], ["medical_history", false], ["surgical_history", false], ["family_history", false], ["social_history", false], ["ros", false],
      ["physical_exam_systems", false], ["nutrition_risk", false], ["lower_extremity", false], ["diabetic_foot_exam", false], ["plan_of_care", false], ["fall_risk", false],
      ["em_time", false], ["prescriptions", false], ["assessment", true], ["attestation_statements", false], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "Established Wound Care",
    description: "Follow-up provider wound care visit.",
    visitTypes: ["EST_WOUND", "FOLLOW_UP", "WOUND_CARE"],
    steps: [
      ["wounds", true], ["problems", false], ["procedures", false], ["physician_orders", false], ["meds", false], ["cc", true], ["vitals", false], ["allergy_list", false],
      ["ros", false], ["physical_exam_systems", false], ["lower_extremity", false], ["plan_of_care", false], ["treatment_notes", false], ["prescriptions", false],
      ["assessment", true], ["attestation_statements", false], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "SNF Established Visit",
    description: "Follow-up wound care visit in a skilled nursing facility, with pressure risk and support surface checks.",
    visitTypes: ["SNF_EST"],
    steps: [
      ["wounds", true], ["problems", false], ["procedures", false], ["physician_orders", false], ["meds", false], ["cc", true], ["vitals", false], ["code_status", false],
      ["allergy_list", false], ["ros", false], ["physical_exam_systems", false], ["braden", false], ["offloading", false], ["plan_of_care", false], ["treatment_notes", false],
      ["assessment", true], ["attestation_statements", false], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "Surveillance Visit",
    description: "Monitoring visit for a healed or stable wound.",
    visitTypes: ["SURVEILLANCE"],
    steps: [
      ["wounds", true], ["cc", true], ["vitals", false], ["problems", false], ["braden", false], ["offloading", false], ["plan_of_care", false], ["physician_orders", false],
      ["assessment", true], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "Provider Ultrasound Mist Therapy",
    description: "Ultrasound mist therapy performed by the provider or NP / WCN.",
    visitTypes: ["PROV_MIST", "NPWCN_MIST"],
    steps: [
      ["wounds", true], ["problems", false], ["procedures", false], ["physician_orders", false], ["meds", false], ["cc", true], ["vitals", false], ["allergy_list", false],
      ["ros", false], ["physical_exam_systems", false], ["lower_extremity", false], ["plan_of_care", false], ["treatment_notes", true], ["prescriptions", false],
      ["attestation_statements", false], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "Actigraft Application",
    description: "Application of Actigraft or another cell and tissue product.",
    visitTypes: ["ACTIGRAFT"],
    steps: [
      ["wounds", true], ["problems", false], ["procedures", false], ["ctp", true], ["physician_orders", false], ["cc", true], ["vitals", false], ["plan_of_care", false],
      ["assessment", false], ["attestation_statements", false], ["progress", false], ["superbill", false], ["signatures", false],
    ],
  },
  {
    name: "Ankle Brachial Index Assessment",
    description: "ABI study with the lower extremity assessment.",
    visitTypes: ["ABI"],
    steps: [["lower_extremity", true], ["vitals", false], ["problems", false], ["physician_orders", false], ["progress", false], ["superbill", false], ["signatures", false]],
  },
  {
    name: "Principal Care Management",
    description: "Monthly principal care management for one serious chronic condition.",
    visitTypes: ["PCM"],
    steps: [["pcm", true], ["problems", false], ["meds", false], ["plan_of_care", false], ["em_time", false], ["progress", false], ["superbill", false], ["signatures", false]],
  },
  {
    name: "Provider Orders",
    description: "Orders written outside a visit.",
    visitTypes: ["PROVIDER_ORDERS"],
    steps: [["wounds", false], ["problems", false], ["physician_orders", true], ["signatures", false]],
  },
  {
    name: "Communication Log",
    description: "A call or message with the patient, family or another provider.",
    visitTypes: ["COMM_LOG"],
    steps: [["communication_log", true], ["narrative_notes", false]],
  },
  {
    name: "Medical Records / Data Entry",
    description: "Entering history and records received from elsewhere.",
    visitTypes: ["RECORDS", "DATA_ENTRY"],
    steps: [["narrative_notes", false], ["problems", false], ["allergy_list", false], ["meds", false], ["medical_history", false], ["surgical_history", false], ["family_history", false], ["social_history", false]],
  },

  {
    name: "Hyperbaric Oxygen Treatment",
    description: "Hyperbaric session — pretreatment assessment, safety checklist, treatment record and the superbill.",
    visitTypes: ["HBO"],
    steps: [
      ["hbo_pretreatment", true],
      ["hbo_safety", true],
      ["hbo_treatment", true],
      ["wounds", false],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  {
    name: "Transcutaneous Oximetry (TCOM)",
    description: "TcPO2 study with oxygen challenge.",
    visitTypes: ["TCOM"],
    steps: [
      ["cc", false],
      ["vitals", false],
      ["tcom", true],
      ["wounds", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  // ---------------- Primary-care pack ----------------
  {
    name: "Primary Care Visit",
    description: "Acute, chronic-condition and annual physical visits — history, vitals, exam, assessment and plan, superbill.",
    visitTypes: ["SICK", "PHYSICAL", "CHRONIC"],
    steps: [
      ["cc", true],
      ["vitals", true],
      ["problems", false],
      ["ros", false],
      ["physical_exam_systems", false],
      ["exam", true],
      ["assessment", true],
      ["meds", false],
      ["diabetes_flowsheet", false],
      ["hypertension_flowsheet", false],
      ["asthma_control", false],
      ["preventive_care", false],
      ["procedures", false],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  {
    name: "Annual Wellness Visit",
    description: "Medicare AWV / wellness visit — health risk assessment, screenings, immunizations and the prevention plan.",
    visitTypes: ["AWV", "WELL"],
    steps: [
      ["cc", false],
      ["vitals", true],
      ["problems", false],
      ["awv_hra", true],
      ["phq9", false],
      ["audit_c", false],
      ["fall_risk", false],
      ["preventive_care", true],
      ["immunizations", false],
      ["family_history", false],
      ["social_history", false],
      ["advance_directives", false],
      ["meds", false],
      ["assessment", true],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
  {
    name: "Well-Child Visit",
    description: "Bright Futures well-child visit — growth, development, screening, immunizations and anticipatory guidance.",
    visitTypes: ["WELL_CHILD"],
    steps: [
      ["cc", false],
      ["vitals", true],
      ["well_child", true],
      ["immunizations", false],
      ["exam", true],
      ["assessment", true],
      ["progress", false],
      ["superbill", false],
      ["signatures", false],
    ],
  },
];

// Documentation view parts: facesheet, note, problems, meds, wounds, documents, superbill, signatures, attachments, doc:<key>.
export const VIEW_PARTS: Record<string, string> = {
  facesheet: "Face sheet (demographics & insurance)",
  note: "Progress note (SOAP)",
  problems: "Problem list, allergies & medications",
  wounds: "Wound assessments",
  documents: "All completed documents",
  superbill: "Superbill (diagnoses & procedures)",
  signatures: "Signatures",
  attachments: "Scans & test result files (list)",
};

export const STANDARD_VIEWS: { name: string; description: string; parts: string[] }[] = [
  { name: "Progress Note", description: "The signed progress note", parts: ["note", "signatures"] },
  { name: "Progress Note + Physician Orders", description: "Progress note with this visit's orders", parts: ["note", "doc:physician_orders", "signatures"] },
  { name: "All Documentation", description: "Everything documented on this visit", parts: ["facesheet", "note", "wounds", "documents", "superbill", "signatures", "attachments"] },
  { name: "Facility Documentation", description: "For the facility chart (SNF / ALF)", parts: ["note", "wounds", "doc:treatment_notes", "doc:wound_management_plan", "doc:physician_orders", "signatures"] },
  { name: "Physician Orders + Facesheet", description: "Orders with patient demographics", parts: ["facesheet", "doc:physician_orders", "signatures"] },
  { name: "Patient Referral Sheet", description: "Referral packet", parts: ["facesheet", "problems", "wounds", "doc:plan_of_care"] },
  { name: "Home Health Agency", description: "Orders and plan for the home health agency", parts: ["facesheet", "doc:physician_orders", "doc:wound_management_plan", "wounds"] },
  { name: "Ancillary Service Order", description: "Ancillary orders with coding", parts: ["facesheet", "doc:physician_orders", "superbill"] },
  {
    name: "Visit Report",
    description: "Every document of the visit, in the order of the practice's visit report",
    parts: [
      "doc:ros",
      "doc:vitals_additional",
      "doc:physical_exam_systems",
      "problems",
      "doc:physician_orders",
      "superbill",
      "note",
      "doc:plan_of_care",
      "doc:treatment_goals",
      "doc:scribe_statement",
      "doc:lower_extremity",
      "wounds",
      "doc:wound_assessment_details",
      "doc:debridement",
      "doc:unna_boot",
      "doc:ctp",
      "doc:allergy_list",
      "signatures",
    ],
  },
  { name: "Wound PCR", description: "Wound progress and care record", parts: ["wounds", "doc:treatment_notes", "doc:procedures"] },
];
