-- CreateTable
CREATE TABLE "IntakeCase" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "practiceId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "stage" TEXT NOT NULL DEFAULT 'DATA_ENTRY',
    "priority" TEXT NOT NULL DEFAULT 'NORMAL',
    "ownerId" TEXT,
    "holdReason" TEXT,
    "stageChangedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "referralDate" DATETIME,
    "referralSourceType" TEXT,
    "referralSourceName" TEXT,
    "referralContactName" TEXT,
    "referralContactPhone" TEXT,
    "referralContactFax" TEXT,
    "servicesRequested" TEXT,
    "referralNotes" TEXT,
    "dataEntryCompletedAt" DATETIME,
    "payerId" TEXT,
    "planSegment" TEXT,
    "memberId" TEXT,
    "eligibilityStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "coverageEffectiveDate" DATETIME,
    "coverageTermDate" DATETIME,
    "copayCents" INTEGER,
    "deductibleCents" INTEGER,
    "deductibleMetCents" INTEGER,
    "coinsurancePercent" INTEGER,
    "outOfPocketRemainingCents" INTEGER,
    "verifiedAt" DATETIME,
    "verifiedWith" TEXT,
    "verificationReference" TEXT,
    "benefitsNotes" TEXT,
    "authRequired" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "authStatus" TEXT NOT NULL DEFAULT 'NOT_REQUIRED',
    "authNumber" TEXT,
    "authSubmittedAt" DATETIME,
    "authDecisionAt" DATETIME,
    "authStartDate" DATETIME,
    "authEndDate" DATETIME,
    "authVisitsApproved" INTEGER,
    "authNotes" TEXT,
    "referralRequired" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "referralStatus" TEXT NOT NULL DEFAULT 'NOT_REQUIRED',
    "referralNumber" TEXT,
    "pccSentAt" DATETIME,
    "pccNotes" TEXT,
    "assignedProviderId" TEXT,
    "networkOverrideNote" TEXT,
    "approvedForServiceAt" DATETIME,
    "consentTreatment" BOOLEAN NOT NULL DEFAULT false,
    "consentHipaa" BOOLEAN NOT NULL DEFAULT false,
    "consentFinancial" BOOLEAN NOT NULL DEFAULT false,
    "consentAssignment" BOOLEAN NOT NULL DEFAULT false,
    "consentsCompletedAt" DATETIME,
    "pcpName" TEXT,
    "pcpPhone" TEXT,
    "pcpFax" TEXT,
    "referralAppStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED',
    "scheduledAt" DATETIME,
    "careStatus" TEXT,
    "providerBrief" TEXT,
    "closedReason" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "IntakeCase_practiceId_fkey" FOREIGN KEY ("practiceId") REFERENCES "Practice" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "IntakeCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "IntakeCase_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "IntakeCase_payerId_fkey" FOREIGN KEY ("payerId") REFERENCES "Payer" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "IntakeCase_assignedProviderId_fkey" FOREIGN KEY ("assignedProviderId") REFERENCES "RenderingProvider" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "IntakeActivity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "caseId" TEXT NOT NULL,
    "userId" TEXT,
    "stage" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "note" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "IntakeActivity_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "IntakeCase" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "IntakeActivity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "IntakeCase_practiceId_stage_idx" ON "IntakeCase"("practiceId", "stage");

